pipeline {
    agent any
    environment {
        SONAR_SERVER = 'SonarLocal'
        SONAR_PROJECT_KEY = 'HeroEngine' 
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Preparar SonarScanner') {
            steps {
                bat 'dotnet tool install --global dotnet-sonarscanner || exit 0'
            }
        }
        stage('SonarQube Begin') {
            steps {
                withSonarQubeEnv(SONAR_SERVER) {
                    bat "dotnet sonarscanner begin /k:\"${SONAR_PROJECT_KEY}\" /d:sonar.cs.opencover.reportsPaths=\"**/coverage.opencover.xml\""
                }
            }
        }
        stage('Build') {
            steps {
                bat 'dotnet build'
            }
        }
        stage('Test') {
            steps {
                bat 'dotnet test --no-build --collect:"XPlat Code Coverage" --DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'
            }
        }
        stage('SonarQube End') {
            steps {
                withSonarQubeEnv(SONAR_SERVER) {
                    bat "dotnet sonarscanner end /d:sonar.token=\"%SONAR_TOKEN%\""
                }
            }
        }
    }
}